"""add_coluna identificador_usuario na tb_usuario

Revision ID: 0c1756eec78d
Revises: 5e5e1226689a
Create Date: 2026-03-28 17:30:57.913811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0c1756eec78d'
down_revision: Union[str, Sequence[str], None] = '5e5e1226689a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identificador_usuario', sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_usuario', schema=None) as batch_op:
        batch_op.drop_column('identificador_usuario')

    # ### end Alembic commands ###
