"""add_tb_aporte

Revision ID: 5e5e1226689a
Revises: 9da1028d9321
Create Date: 2026-03-28 15:32:56.076656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5e5e1226689a'
down_revision: Union[str, Sequence[str], None] = '9da1028d9321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_aporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome_empresa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor_aporte', sa.Float(), nullable=False),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prazo', sa.Integer(), nullable=False),
    sa.Column('taxa', sa.Float(), nullable=False),
    sa.Column('status_pagamento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_aporte')
    # ### end Alembic commands ###
