"""atualiza_colunas_tb_aporte

Revision ID: 73d73e9df708
Revises: 0c1756eec78d
Create Date: 2026-04-12 19:49:20.742111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '73d73e9df708'
down_revision: Union[str, Sequence[str], None] = '0c1756eec78d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_aporte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_aporte_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('fundo_origem_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('nome_fundo_investidor', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('empresa_sacada_nome', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('cnpj_sacado_limpo', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('valor_aporte_compra', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valor_mercado_atual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('taxa_retorno_pre_fixada', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('prazo_vencimento_dias', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quantidade_papeis_adquiridos', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('score_risco_interno', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status_prazo_vencimento', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('bloco_liquidez_setorial', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('categoria_tecnica_ativo', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('codigo_identificacao_isin', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('codigo_identificacao_selic', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('data_referencia_competencia', sa.Date(), nullable=True))
        batch_op.drop_column('nome_empresa')
        batch_op.drop_column('taxa')
        batch_op.drop_column('categoria')
        batch_op.drop_column('status_pagamento')
        batch_op.drop_column('valor_aporte')
        batch_op.drop_column('cnpj')
        batch_op.drop_column('prazo')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_aporte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prazo', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cnpj', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('valor_aporte', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status_pagamento', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('categoria', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('taxa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nome_empresa', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('data_referencia_competencia')
        batch_op.drop_column('codigo_identificacao_selic')
        batch_op.drop_column('codigo_identificacao_isin')
        batch_op.drop_column('categoria_tecnica_ativo')
        batch_op.drop_column('bloco_liquidez_setorial')
        batch_op.drop_column('status_prazo_vencimento')
        batch_op.drop_column('score_risco_interno')
        batch_op.drop_column('quantidade_papeis_adquiridos')
        batch_op.drop_column('prazo_vencimento_dias')
        batch_op.drop_column('taxa_retorno_pre_fixada')
        batch_op.drop_column('valor_mercado_atual')
        batch_op.drop_column('valor_aporte_compra')
        batch_op.drop_column('cnpj_sacado_limpo')
        batch_op.drop_column('empresa_sacada_nome')
        batch_op.drop_column('nome_fundo_investidor')
        batch_op.drop_column('fundo_origem_id')
        batch_op.drop_column('id_aporte_uuid')

    # ### end Alembic commands ###
