"""atualiza schema aporte final sprint

Revision ID: 8bab438c0c7c
Revises: f1734487ccc4
Create Date: 2026-04-18 14:11:40.472722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8bab438c0c7c'
down_revision: Union[str, Sequence[str], None] = 'f1734487ccc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_aporte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_vencimento', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('flag_outlier_valor', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('documento_investidor_cpf_cnpj',
               nullable=False)
        batch_op.alter_column('fundo_origem_id',
               nullable=False)
        batch_op.alter_column('nome_fundo_investidor',
               nullable=False)
        batch_op.alter_column('empresa_sacada_nome',
               nullable=False)
        batch_op.alter_column('cnpj_sacado_limpo',
               nullable=False)
        batch_op.alter_column('valor_aporte_compra',
               nullable=False)
        batch_op.alter_column('valor_mercado_atual',
               nullable=False)
        batch_op.alter_column('quantidade_papeis_adquiridos',
               nullable=False)
        batch_op.alter_column('data_referencia_competencia',
               nullable=False)
        batch_op.alter_column('prazo_vencimento_dias',
               nullable=False)
        batch_op.alter_column('status_prazo_vencimento',
               nullable=False)
        batch_op.alter_column('taxa_retorno_pre_fixada',
               nullable=False)
        batch_op.alter_column('bloco_liquidez_setorial',
               nullable=False)
        batch_op.alter_column('categoria_tecnica_ativo',
               nullable=False)
        batch_op.alter_column('score_risco_interno',
               nullable=False)
        batch_op.create_index(batch_op.f('ix_tb_aporte_documento_investidor_cpf_cnpj'), ['documento_investidor_cpf_cnpj'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_aporte_id_aporte_uuid'), ['id_aporte_uuid'], unique=False)
        batch_op.drop_column('investidor_id')
        batch_op.drop_column('email_investidor')
        batch_op.drop_column('nome_investidor')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_aporte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_investidor', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email_investidor', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('investidor_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_tb_aporte_id_aporte_uuid'))
        batch_op.drop_index(batch_op.f('ix_tb_aporte_documento_investidor_cpf_cnpj'))
        batch_op.alter_column('score_risco_interno',
               nullable=True)
        batch_op.alter_column('categoria_tecnica_ativo',
               nullable=True)
        batch_op.alter_column('bloco_liquidez_setorial',
               nullable=True)
        batch_op.alter_column('taxa_retorno_pre_fixada',
               nullable=True)
        batch_op.alter_column('status_prazo_vencimento',
               nullable=True)
        batch_op.alter_column('prazo_vencimento_dias',
               nullable=True)
        batch_op.alter_column('data_referencia_competencia',
               nullable=True)
        batch_op.alter_column('quantidade_papeis_adquiridos',
               nullable=True)
        batch_op.alter_column('valor_mercado_atual',
               nullable=True)
        batch_op.alter_column('valor_aporte_compra',
               nullable=True)
        batch_op.alter_column('cnpj_sacado_limpo',
               nullable=True)
        batch_op.alter_column('empresa_sacada_nome',
               nullable=True)
        batch_op.alter_column('nome_fundo_investidor',
               nullable=True)
        batch_op.alter_column('fundo_origem_id',
               nullable=True)
        batch_op.alter_column('documento_investidor_cpf_cnpj',
               nullable=True)
        batch_op.drop_column('data_criacao')
        batch_op.drop_column('flag_outlier_valor')
        batch_op.drop_column('data_vencimento')

    # ### end Alembic commands ###
