"""cria tb_usuario e tb_aporte

Migração inicial. Substitui as seis migrações anteriores, que descreviam um schema
que a aplicação não usa: a criação de `tb_usuario` declarava as colunas `nome`,
`email` e `senha_hash`, e nenhuma migração posterior as renomeava para
`nome_usuario`, `email_usuario` e `senha_hash_usuario`. O banco em uso na época
tinha sido ajustado por fora do histórico, então `upgrade head` num banco vazio
produzia tabelas inutilizáveis.

Com a saída do Supabase não há mais banco legado a preservar, e o histórico foi
regerado a partir dos modelos em `domain/models.py`. O índice único de
`tb_usuario.email_usuario`, que o modelo antigo declarava mas nunca chegou ao
banco, agora existe de verdade.

Revision ID: e4bebb3f7556
Revises: 
Create Date: 2026-09-06

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e4bebb3f7556'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_aporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aporte_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('documento_investidor_cpf_cnpj', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fundo_origem_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome_fundo_investidor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('empresa_sacada_nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cnpj_sacado_limpo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor_aporte_compra', sa.Float(), nullable=False),
    sa.Column('valor_mercado_atual', sa.Float(), nullable=False),
    sa.Column('quantidade_papeis_adquiridos', sa.Float(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_referencia_competencia', sa.Date(), nullable=False),
    sa.Column('prazo_vencimento_dias', sa.Integer(), nullable=False),
    sa.Column('status_prazo_vencimento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('taxa_retorno_pre_fixada', sa.Float(), nullable=False),
    sa.Column('bloco_liquidez_setorial', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('categoria_tecnica_ativo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('codigo_identificacao_isin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('score_risco_interno', sa.Float(), nullable=False),
    sa.Column('flag_outlier_valor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_aporte_documento_investidor_cpf_cnpj'), 'tb_aporte', ['documento_investidor_cpf_cnpj'], unique=False)
    op.create_index(op.f('ix_tb_aporte_id_aporte_uuid'), 'tb_aporte', ['id_aporte_uuid'], unique=False)
    op.create_table('tb_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_usuario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome_usuario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email_usuario', sa.String(), nullable=False),
    sa.Column('identificador_usuario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senha_hash_usuario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_usuario_email_usuario'), 'tb_usuario', ['email_usuario'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_usuario_email_usuario'), table_name='tb_usuario')
    op.drop_table('tb_usuario')
    op.drop_index(op.f('ix_tb_aporte_id_aporte_uuid'), table_name='tb_aporte')
    op.drop_index(op.f('ix_tb_aporte_documento_investidor_cpf_cnpj'), table_name='tb_aporte')
    op.drop_table('tb_aporte')
    # ### end Alembic commands ###
