"""add_dados_investidor_aporte

Revision ID: f1734487ccc4
Revises: 73d73e9df708
Create Date: 2026-04-15 23:37:51.747317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f1734487ccc4'
down_revision: Union[str, Sequence[str], None] = '73d73e9df708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_aporte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('investidor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('nome_investidor', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('documento_investidor_cpf_cnpj', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('email_investidor', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_aporte', schema=None) as batch_op:
        batch_op.drop_column('email_investidor')
        batch_op.drop_column('documento_investidor_cpf_cnpj')
        batch_op.drop_column('nome_investidor')
        batch_op.drop_column('investidor_id')

    # ### end Alembic commands ###
